# in this code we extend the SWAP test over N qubits to see how the error scales as we increase the number of shots through the circuit

import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from qiskit.quantum_info import SparsePauliOp
from qiskit.circuit.library import efficient_su2
from qiskit_ibm_runtime import QiskitRuntimeService, Session
from qiskit_ibm_runtime import EstimatorV2 as Estimator
from qiskit_aer import AerSimulator
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
import vqe
import testing_swap
from qiskit import QuantumCircuit, ClassicalRegister, transpile
from qiskit.circuit.library import CSwapGate


def decompose(ground_state, dimension):
    #print(ground_state)
    # suppose we are given a quantum circuit from the VQE
    # we will perform SWAP tests on the state generated by the quantum circuit and the 2 ground states of transverse field Ising model
    # we will then compare the error in the SWAP test as we increase the number of
    basis = testing_swap.basiss(dimension)
    basis=np.array(basis)
    # we identify the two ground states that we want to perform the SWAP test on.
    state1 = basis[0]
    state2 = basis[2**dimension-1]
    states=[state1, state2]
    #print(states)
    s2s=[]
    repeats=30
    for t in range(repeats):
        s2=[]
        for state in states:
            qc=QuantumCircuit(2*dimension +1)
            # on the first dimension qubits we first initialize zeros
            qc.initialize(ground_state, range(dimension), normalize=True)
            # on the second dimension qubits we initialize the state with the basis state we want to
            qc.initialize(state, range(dimension, 2*dimension), normalize=True)
            # now we will compute the fidelity between these two states
            qc.initialize([1,0],2*dimension, normalize=True)
            # this is the extra qubit storing the information about the overlap
            qc.add_register(ClassicalRegister(1, 'c'))
            qc.h(2*dimension)
            # now we want to perform a controlled SWAP on the circuit from VQE and the basis state
            for i in range(dimension):
                qc.append(CSwapGate(), [2*dimension, i, dimension+i])
            qc.h(2*dimension)
            shots=1000
            simulator = AerSimulator(method='statevector')   
            qc.measure(2*dimension,0)
            job = simulator.run(qc, shots=shots)  # Run 100 times
            result = job.result()
            counts = result.get_counts(qc)
            num_zeros = counts.get('0', 0)
            s2.append(np.abs(2*(num_zeros / shots)-1.0))
        # so now we have the intersection with both ground states
        s2=np.array(s2)
        s2=np.abs(np.sum(s2)-1.0)
        s2s.append(s2)
    s2s=np.array(s2s)
    return s2s.mean(), s2s.std()
    # we will then compare the error in the SWAP test as we increase the number of shots in the circuit
def error_withoutsecondstate(ground_state, dimension):
    basis = testing_swap.basiss(dimension)
    basis=np.array(basis)
    # we identify the two ground states that we want to perform the SWAP test on.
    state1 = basis[0]
    state2 = basis[2**dimension-1]
    states=[state1, state2]
    # we now add the excitations defined by spin flips on the ground state
    for i in range(dimension):
        index=2**i
        states.append(basis[index])
    s2s=[]
    singles=[]
    excitations=[]
    # we will also account for doing the SWAP test on all the excited states
    repeats=30
    for t in range(repeats):
        s2=[]
        single_state_error=[]
        excitation=[]
        for j,state in enumerate(states):
            qc=QuantumCircuit(2*dimension +1)
            # on the first dimension qubits we first initialize zeros
            qc.initialize(ground_state, range(dimension), normalize=True)
            # on the second dimension qubits we initialize the state with the basis state we want to
            qc.initialize(state, range(dimension, 2*dimension), normalize=True)
            # now we will compute the fidelity between these two states
            qc.initialize([1,0],2*dimension, normalize=True)
            # this is the extra qubit storing the information about the overlap
            qc.add_register(ClassicalRegister(1, 'c'))
            qc.h(2*dimension)
            # now we want to perform a controlled SWAP on the circuit from VQE and the basis state
            for i in range(dimension):
                qc.append(CSwapGate(), [2*dimension, i, dimension+i])
            qc.h(2*dimension)
            shots=1000
            simulator = AerSimulator(method='statevector')   
            qc.measure(2*dimension,0)
            job = simulator.run(qc, shots=shots)  # Run 100 times
            result = job.result()
            counts = result.get_counts(qc)
            num_zeros = counts.get('0', 0)
            if (j==1 or j==0): 
                s2.append(np.abs(2*(num_zeros / shots)-1.0))
            if j==1:
                single_state_error.append(np.abs(2*(num_zeros / shots)-1.0))
            excitation.append(np.abs(2*(num_zeros / shots)-1.0))
        # so now we have the intersection with both ground states
        s2=np.array(s2)
        s2=np.abs(np.sum(s2)-1.0)
        s2s.append(s2)
        single_state_error=np.array(single_state_error)
        single_state_error=np.abs(single_state_error-1.0)
        singles.append(single_state_error)
        excitation=np.array(excitation)
        excitation=np.abs(excitation-1.0)
        excitations.append(excitation)
    singles=np.array(singles)
    s2s=np.array(s2s)
    excitations=np.array(excitations)
    return s2s.mean(), s2s.std(), singles.mean(), singles.std(), excitations.mean(), excitations.std()
    # so now we extend not only to degenerate error, but to single state error
def error_singles():
    np.random.seed(37)
    dimension=5
    # we will fix the dimension to be 4 or 5 and track the performance of the error as we increase h
    hs = np.linspace(-0.2,2.0,15)
    errors=[]
    stds=[]
    errors1=[]
    stds1=[]
    for h in hs:
        ground_state, cost_history_dict = vqe.variational_quantum_eigensolver(dimension, h=h)
        error, std, error1, std1=error_withoutsecondstate(ground_state, dimension)
        errors.append(error)
        stds.append(std)
        errors1.append(error1)
        stds1.append(std1)
    plt.figure(figsize=(10, 6))
    plt.plot(hs, errors, label=f"Average error with SWAP over both spin up and spin down")
    plt.fill_between(hs, np.array(errors) - np.array(stds), np.array(errors) + np.array(stds), alpha=0.2, label=f"Error Variance with SWAP over both spin up and spin down")
    plt.plot(hs, errors1, label=f"Average error with SWAP over only spin up")
    plt.fill_between(hs, np.array(errors1) - np.array(stds1), np.array(errors1) + np.array(stds1), alpha=0.2, label=f"Error Variance with SWAP over only spin up")
    plt.xlabel("Magnetic field strength (h)")
    plt.ylabel("Average Error")
    plt.title(f"SWAP Test Error vs Magnetic field strength for the quantum Ising model: Alternative ansatz, {dimension} qubits")
    plt.legend()
    plt.savefig(f"swap_test_error_ising_singles_{dimension}_alternative.png")
    plt.show()
def error():
    np.random.seed(37)
    dimensions=[2,3,4,5]
    # we will also vary the magnetic field h
    hs = [0.0, 0.2, 0.5, 1.0, 2.0]
    errors=[[],[],[],[],[]]
    stds=[[],[],[],[],[]]
    # we prepare the error and standard deviation lists for various h
    for dimension in dimensions:
        counter=0
        for h in hs:
            ground_state, cost_history_dict = vqe.variational_quantum_eigensolver(dimension, h=h)
            error, std=decompose(ground_state, dimension)
            errors[counter].append(error)
            stds[counter].append(std)
            counter=counter+1
    # now we want to plot the errors for various Hilbert space sizes and we will label different magnetic field strengths
    plt.figure(figsize=(10, 6))
    Ns=[2**d for d in dimensions]
    # we will want a colorbar of standard deviations
    for i,h in enumerate(hs):
        plt.plot(Ns, errors[i], label=f"Average error with magnetic field h={h}")
        # we will need to convert errors[i] into numpy, it doesn't work otherwise
        plt.fill_between(Ns, np.array(errors[i]) - np.array(stds[i]), np.array(errors[i]) + np.array(stds[i]), alpha=0.2, label=f"Error Variance with h={h}")
    plt.xlabel("Hilbert space size (N)")
    plt.ylabel("Average Error")
    plt.title("SWAP Test Error vs Hilbert Space size for the Ising Model: Alternative ansatz")
    plt.legend()
    plt.savefig("swap_test_error_ising_2.png")
    plt.show()
if __name__ == "__main__":
    error()
